# Auto-generated by the bruce-tui release workflow — do not edit by hand.
# Template: https://github.com/soydanielsierradev/bruce-tui/blob/main/packaging/homebrew/bruce.rb
class Bruce < Formula
  desc "Terminal workspace for Claude Code"
  homepage "https://github.com/soydanielsierradev/bruce-tui"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${BASE}/bruce-aarch64-apple-darwin.tar.gz"
      sha256 "${SHA_ARM}"
    end
    on_intel do
      url "${BASE}/bruce-x86_64-apple-darwin.tar.gz"
      sha256 "${SHA_INTEL}"
    end
  end

  on_linux do
    on_intel do
      url "${BASE}/bruce-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${SHA_LINUX}"
    end
  end

  def install
    bin.install "bruce"
  end

  def caveats
    <<~CAVEAT
      Bruce runs the Claude CLI inside its workspace. Install Claude Code and
      make sure `claude` is on your PATH: https://docs.claude.com/claude-code
    CAVEAT
  end

  test do
    assert_match "bruce", shell_output("#{bin}/bruce --version")
  end
end
